blueprint:
  name: Rainbow Flow for 11 Lights
  description: >
    Create a rainbow flow effect for 11 light bulbs. The lights transition in sequence, cycling through red, orange, yellow, green, blue, indigo, and violet.
  domain: automation
  input:
    lights:
      name: Light Entities
      description: >
        List of 11 light entities to apply the effect.
      selector:
        entity:
          domain: light
          multiple: true
    transition_speed:
      name: Transition Speed
      description: Time in seconds for each transition.
      default: 1
      selector:
        number:
          min: 0.1
          max: 10
          unit_of_measurement: seconds
    start_color:
      name: Starting Light Color
      description: The first light color in the sequence.
      default: red
      selector:
        select:
          options:
            - red
            - orange
            - yellow
            - green
            - blue
            - indigo
            - violet

variables:
  colors: 
    - red
    - orange
    - yellow
    - green
    - blue
    - indigo
    - violet

trigger:
  - platform: time_pattern
    seconds: "/{{ transition_speed }}"

action:
  - repeat:
      count: "{{ lights | count }}"
      sequence:
        - variables:
            current_index: "{{ (repeat.index + cycle_offset) % colors | length }}"
        - service: light.turn_on
          target:
            entity_id: "{{ lights[repeat.index - 1 }}
                      data:
            color_name: "{{ colors[current_index] }}"
            transition: "{{ transition_speed }}"
        - delay:
            seconds: "{{ transition_speed }}"
  - service: automation.trigger
    data:
      entity_id: "{{ this.entity_id }}"
variables:
  cycle_offset: >
    {% set start_index = colors.index(start_color) %}
    {{ (repeat.index - 1 + start_index) % colors | length }}
mode: restart
